import { useCloud, CloudSettings } from './cloud';
import { useVersions, VersionOptions } from './versions';
import { useEffect, useRef, useState } from 'react';
import { Home, Boxes, Settings, ArrowUpRight, ChevronRight, Play, SlidersHorizontal, ShieldCheck, Sparkles, X, Check, Search, Monitor, UserRound, Mountain, Zap } from 'lucide-react';

type Page = 'Home' | 'Mods' | 'Settings';
type Preferences = { ram: number; version: string; motion: boolean; mods: string[] };
const defaults: Preferences = { ram: 4, version: 'latest-release', motion: true, mods: ['sodium', 'iris'] };
function load(): Preferences {
  try { const p = JSON.parse(localStorage.getItem('lyra-settings') || 'null'); return p ? { ram: Number.isInteger(p.ram) && p.ram >= 2 && p.ram <= 16 ? p.ram : 4, version: typeof p.version === 'string' ? p.version : 'latest-release', motion: typeof p.motion === 'boolean' ? p.motion : true, mods: Array.isArray(p.mods) ? p.mods.filter((x: unknown) => typeof x === 'string') : defaults.mods } : defaults; } catch { return defaults; }
}
const mods = [ { id: 'sodium', name: 'Sodium', type: 'Teljesítmény', description: 'Gyorsabb renderelés, simább kalandok.', icon: Zap, color: 'green' }, { id: 'iris', name: 'Iris Shaders', type: 'Grafika', description: 'Új fények és hangulat a világodban.', icon: Sparkles, color: 'purple' }, { id: 'lithium', name: 'Lithium', type: 'Teljesítmény', description: 'Hatékonyabb működés a háttérben.', icon: Boxes, color: 'blue' } ];
export default function App() {
  const cloudService = useCloud();
  const remote = cloudService.cloud?.content;
  const { manifest, error: versionError, loading: versionsLoading, refresh } = useVersions();
  const [page, setPage] = useState<Page>('Home');
  const [prefs, setPrefs] = useState(load);
  const [query, setQuery] = useState('');
  const [modal, setModal] = useState<'play' | 'login' | null>(null);
  const [saveError, setSaveError] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { try { localStorage.setItem('lyra-settings', JSON.stringify(prefs)); setSaveError(false); } catch { setSaveError(true); } }, [prefs]);
  useEffect(() => { if (modal) dialog.current?.showModal(); else dialog.current?.close(); }, [modal]);
  const update = (patch: Partial<Preferences>) => setPrefs(p => ({ ...p, ...patch }));
  return <div className={`app ${prefs.motion ? '' : 'reduce-motion'}`} style={remote ? { '--lyra-accent': remote.accent } as import('react').CSSProperties : undefined}>
    <aside className="sidebar">
      <div className="brand"><img src="./lyra-mark.svg" alt="Lyra embléma"/><div>LYRA<span>CLIENT</span></div></div>
      <div className="nav-label">WORKSPACE</div>
      <nav aria-label="Fő navigáció">{([{ name: 'Home', icon: Home }, { name: 'Mods', icon: Boxes }, { name: 'Settings', icon: Settings }] as const).map(({ name, icon: Icon }) => <button key={name} className={page === name ? 'nav active' : 'nav'} onClick={() => setPage(name)} aria-current={page === name ? 'page' : undefined}><Icon size={19}/>{name}{page === name && <span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="build-label"><span/> EARLY ACCESS <b>0.3.1</b></div><button className="account" onClick={() => setModal('login')}><div className="avatar"><UserRound size={20}/></div><div>Vendég játékos<small>Microsoft-fiók hozzáadása</small></div><ChevronRight size={15}/></button></div>
    </aside>
    <main><header><div className="breadcrumb">Lyra Client <ChevronRight size={13}/> <strong>{page}</strong></div><span className="preview"><span/> GUI PREVIEW</span></header>
      <div className="content"><div className="page-heading"><div><div className="eyebrow">YOUR WORLD. YOUR WAY.</div><h1>{page === 'Home' ? 'Üdv a Lyrában.' : page === 'Mods' ? 'Tedd a sajátoddá.' : 'Minden a helyén.'}</h1><p>{page === 'Home' ? 'Egy hely minden kalandodnak.' : page === 'Mods' ? 'Állítsd össze a következő kalandod eszköztárát.' : 'Hangold a klienst a saját játékstílusodra.'}</p></div><div className="heading-mark"><img src="./lyra-mark.svg" alt=""/></div></div>
      {page === 'Home' && <>{remote?.announcement && <div className="notice">{remote.announcement}</div>}{cloudService.cloud?.update.status === 'ready' && <div className="notice"><span>Új launcherfrissítés készen áll.</span><button onClick={() => void cloudService.install()}>Újraindítás és telepítés</button></div>}<div className="version-status" role="status"><span>{versionsLoading ? 'Verziók frissítése…' : versionError || (manifest?.cached ? 'Offline: a mentett verziólista látható.' : `${manifest?.versions.length ?? 0} verzió • Automatikus frissítés 15 percenként`)}<br/>A lista frissül; játékletöltés és indítás még nincs bekötve.</span><button disabled={versionsLoading} onClick={() => void refresh()}>Frissítés</button></div>
        <section className="hero"><div className="stars"/><div className="moon"/><div className="landscape far"/><div className="landscape middle"/><div className="landscape near"/><div className="hero-copy"><span className="pill"><span/> LYRA EXPERIENCE</span><h2>{remote?.title || <>A következő kalandod<br/>itt kezdődik.</>}</h2><p>{remote?.subtitle || <>Ismerős világ. Új perspektíva.<br/>Építs valamit, ami csak a tiéd.</>}</p><span className="hero-caption"><Mountain size={15}/> VÉGTELEN LEHETŐSÉGEK</span></div><div className="scene-label">THE OVERWORLD <span>01 / 03</span></div></section>
        <section className="launch-panel"><div className="game-icon"><Boxes size={28}/></div><div className="game-title"><h3>Minecraft Java</h3><span><i/> Profil előkészítve</span></div><label className="version">JÁTÉKVERZIÓ<select value={prefs.version} onChange={e => update({ version: e.target.value })}><VersionOptions manifest={manifest} selected={prefs.version}/></select></label><button className="play" onClick={() => setModal('play')}><Play size={21} fill="currentColor"/> PLAY <span>GUI DEMÓ</span></button></section>
        <div className="section-heading"><h3>A te kliensed. A te szabályaid.</h3><span>LYRA / 001</span></div><div className="cards"><button className="feature" onClick={() => setPage('Mods')}><div className="feature-top"><Boxes className="purple-text" size={22}/><ArrowUpRight size={17}/></div><h3>Egy kis extra.</h3><p>Fedezd fel a modprofilod.</p><span>{prefs.mods.length} kiválasztott demó mod <ChevronRight size={14}/></span></button><button className="feature" onClick={() => setPage('Settings')}><div className="feature-top"><SlidersHorizontal className="blue-text" size={22}/><ArrowUpRight size={17}/></div><h3>Rád hangolva.</h3><p>Apró beállítások. Saját élmény.</p><span>{prefs.ram} GB memória <ChevronRight size={14}/></span></button><div className="feature status-card"><div className="feature-top"><ShieldCheck size={22}/><span className="tiny-tag">ELSŐ LÉPÉS</span></div><h3>Az alapok készen.</h3><p>A launcher felülete már működik.</p><span>Játékindítás és belépés hamarosan</span></div></div>
      </>}
      {page === 'Mods' && <><div className="notice"><Sparkles size={18}/><span>Demó modprofil — a kapcsolók a választásodat mentik. Modokat még nem töltünk le.</span></div><label className="search"><Search size={18}/><input aria-label="Modok keresése" placeholder="Mod keresése…" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="mod-list">{mods.filter(m => m.name.toLowerCase().includes(query.toLowerCase())).map(m => <article className="mod-row" key={m.id}><div className={`mod-icon ${m.color}`}><m.icon size={25}/></div><div><span className="eyebrow">{m.type}</span><h3>{m.name}</h3><p>{m.description}</p></div><button role="switch" aria-checked={prefs.mods.includes(m.id)} aria-label={`${m.name} kiválasztása`} className={`toggle ${prefs.mods.includes(m.id) ? 'on' : ''}`} onClick={() => update({ mods: prefs.mods.includes(m.id) ? prefs.mods.filter(x => x !== m.id) : [...prefs.mods, m.id] })}><span/></button></article>)}{!mods.some(m => m.name.toLowerCase().includes(query.toLowerCase())) && <p className="empty">Nincs találat erre: „{query}”.</p>}</div></>}
      {page === 'Settings' && <><CloudSettings service={cloudService}/><section className="settings-panel"><h3><Monitor size={20}/> Játékbeállítások</h3><div className="setting-row"><div><h4>Memóriakeret</h4><p>A későbbi játékindításhoz elmentett érték.</p></div><strong className="ram-value">{prefs.ram} GB</strong></div><input aria-label="Memóriakeret GB-ban" className="range" type="range" min="2" max="16" value={prefs.ram} onChange={e => update({ ram: Number(e.target.value) })}/><div className="range-labels"><span>2 GB</span><span>16 GB</span></div><div className="setting-row bordered"><div><h4>Alapértelmezett verzió</h4><p>Ez jelenik meg a Home oldalon.</p></div><select aria-label="Alapértelmezett verzió" value={prefs.version} onChange={e => update({ version: e.target.value })}><VersionOptions manifest={manifest} selected={prefs.version}/></select></div><div className="setting-row bordered"><div><h4>Felületi animációk</h4><p>Finom átmenetek a kliensben.</p></div><button role="switch" aria-checked={prefs.motion} aria-label="Felületi animációk" className={`toggle ${prefs.motion ? 'on' : ''}`} onClick={() => update({ motion: !prefs.motion })}><span/></button></div></section><div className="saved" role="status"><Check size={16}/>{saveError ? 'A beállítások mentése nem sikerült.' : 'A beállításokat automatikusan mentjük ezen a gépen.'}</div><section className="about"><img src="./lyra-mark.svg" alt=""/><div><h3>Lyra Client <span>0.3.1</span></h3><p>Az első fejezet. Electron + React + TypeScript.</p></div></section></>}
      <footer><span>LYRA CLIENT <b>•</b> BUILT FOR YOUR NEXT CHAPTER</span><span>Nem hivatalos Minecraft-projekt.</span></footer></div>
    </main>
    <dialog ref={dialog} onCancel={() => setModal(null)} onClick={e => { if (e.target === e.currentTarget) setModal(null); }} aria-labelledby="dialog-title"><button className="close" aria-label="Bezárás" onClick={() => setModal(null)}><X size={21}/></button><div className="dialog-icon">{modal === 'play' ? <Play size={27}/> : <UserRound size={27}/>}</div><div className="eyebrow">HAMAROSAN A LYRA CLIENTBEN</div><h2 id="dialog-title">{modal === 'play' ? 'A kaland még készül.' : 'A fiókod, hamarosan itt.'}</h2><p>{modal === 'play' ? `A felület készen áll. A Minecraft ${prefs.version} valódi indítása és letöltése a következő fejlesztési szakasz része. Most nem indul játék.` : 'A Microsoft-bejelentkezés még nincs bekötve. Jelenleg vendégként próbálhatod ki a felületet.'}</p><button className="primary" onClick={() => setModal(null)}>Rendben <ChevronRight size={17}/></button></dialog>
  </div>;
}

